dubbo:
  application:
    name: cart-service
  registry:
    protocol: zookeeper
    address: 192.168.142.134:2181
  protocol:
    port: 28814

spring:
  redis:
    host: 192.168.142.134
    port: 6379
    password: java1902
    jedis:
      pool:
        max-active: 66
  datasource:
    url: jdbc:mysql://localhost:3306/v13?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: XsOgU/X/MNmkt8GPza172MH2/q63+yGTWnAIeNE1qTEIqL0MVCuJjAQwsbgO3I47MzEqy2fq1W40Upyf8GaZcw==
    druid:
        initial-size: 10
        max-active: 100
        min-idle: 10
        filter:
          config:
            enabled: true
        connection-properties: config.decrypt=true;config.decrypt.key=${public-key}

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJL01bOtE7n5l9qDGZ8bvrqC2Kym0zLuTMhOR2wps2ociO9QRylC+NjIN7nNLY6FPJUsV753cVOu/hDEJGxnIv8CAwEAAQ==
