spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: jPx3Nwb8yiB2HPGxdDjuFf/LChItnieqy0MJNOmkLQmtfah855Wu1ODw/aaJlIi1vBb23Mk8mGTVsZDAwa4iyw==
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALy6Uu3v8TMjExtStEnIlbGXtSbwQA98Z1zXmsYeOlixUh+S8y4EwAAIf/j36pDnuwH9UkTf1neg2+qDDmZVsx0CAwEAAQ==

dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.142.134:2181
  protocol:
    port: 28810

