dubbo:
  application:
    name: search-web
  registry:
    protocol: zookeeper
    address: 192.168.142.134:2181
server:
  port: 9092

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.142.134
    port: 5672
    username: java1902
    password: 123
    virtual-host: /java1902
