dubbo:
  application:
    name: center-web
  registry:
    protocol: zookeeper
    address: 192.168.142.134:2181
server:
  port: 9090

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.142.134
    port: 5672
    username: java1902
    password: 123
    virtual-host: /java1902

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 10.36.8.8:22122

image:
  server: http://192.168.142.134/



