dubbo:
  application:
    name: center-web
  registry:
    protocol: zookeeper
    address: 192.168.142.134:2181
server:
  port: 9090

spring:
  thymeleaf:
    cache: false

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.142.134:22122

image:
  server: http://192.168.142.134/



